import { Metadata } from "next";
import { siteConfig } from "@/lib/site";

const siteUrl = siteConfig.url;
const ogImageUrl = `${siteUrl}/thumbnail.webp`;

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: siteConfig.name,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  // Note: Google no longer uses keywords meta tag, but keeping for reference
  keywords: [
    // Core Brand & Product
    "Sequence3",
    "Sequence3 AI",
    "Sequence3 platform",
    "Sequence3 software",
    "Sequence3 chatbot",
    
    // AI & Machine Learning
    "AI",
    "Artificial Intelligence",
    "AI Agent",
    "AI Assistant",
    "AI Chatbot",
    "AI Conversational Agent",
    "Agentic AI",
    "Autonomous AI",
    "Explainable AI",
    "XAI",
    "Explainable Artificial Intelligence",
    "Transparent AI",
    "Interpretable AI",
    "AI Reasoning",
    "AI Decision Making",
    "AI-Powered Solutions",
    "Machine Learning",
    "ML",
    "Deep Learning",
    "NLP",
    "Natural Language Processing",
    "Conversational AI",
    "Conversation AI",
    "Chatbot AI",
    "AI Automation",
    "Intelligent Automation",
    "Cognitive Automation",
    
    // Human-in-the-Loop & Control
    "Human-in-the-loop",
    "Human-in-the-loop AI",
    "HITL",
    "AI with Human Oversight",
    "Controlled AI",
    "Human-Centered AI",
    "Collaborative AI",
    "AI-Human Collaboration",
    "Supervised AI",
    "Human Oversight",
    
    // Customer Service & Support
    "Customer Support AI",
    "AI Customer Service",
    "AI Customer Support",
    "Automated Customer Service",
    "Customer Service Automation",
    "Customer Support Automation",
    "Customer Support Software",
    "Customer Service Software",
    "Helpdesk AI",
    "Support Ticket Automation",
    "Customer Care AI",
    "24/7 Customer Support",
    "AI Support Agent",
    "Virtual Support Agent",
    "AI Help Desk",
    
    // Customer Experience & Engagement
    "Customer Experience",
    "CX",
    "Customer Engagement",
    "Customer Communication",
    "Customer Interaction",
    "Customer Relationship Management",
    "CRM",
    "Customer Success",
    "Customer Satisfaction",
    "Customer Retention",
    "Customer Acquisition",
    "Customer Journey",
    "Customer Lifecycle",
    
    // Unified Inbox & Multi-Channel
    "Unified Inbox",
    "Centralized Inbox",
    "Multi-Channel Inbox",
    "Omnichannel Inbox",
    "Unified Communication",
    "Omnichannel Messaging",
    "Multi-Channel Messaging",
    "Cross-Channel Communication",
    "Unified Customer Communication",
    "Channel Integration",
    "Multi-Platform Messaging",
    
    // Social Media Integration
    "Instagram DM Automation",
    "Instagram Direct Message",
    "Instagram Business Tools",
    "Facebook Inbox Automation",
    "Facebook Messenger Automation",
    "Facebook Business Suite",
    "WhatsApp Automation",
    "WhatsApp Business API",
    "WhatsApp Chatbot",
    "Social Media Management",
    "Social Media Automation",
    "Social Media Customer Service",
    "Messenger Bot",
    "Facebook Chatbot",
    "Instagram Chatbot",
    
    // Web Chat & Website
    "Website Chat",
    "Live Chat",
    "Website Chatbot",
    "Web Chat Automation",
    "Live Chat Automation",
    "Chat Widget",
    "Website Support",
    "Online Chat",
    "Web Messaging",
    
    // Intent & Sentiment Analysis
    "Intent Detection",
    "Intent Recognition",
    "Intent Classification",
    "Customer Intent",
    "User Intent",
    "Intent Analysis",
    "Sentiment Analysis",
    "Sentiment Detection",
    "Emotion Detection",
    "Customer Sentiment",
    "Text Sentiment Analysis",
    "Sentiment Scoring",
    "Mood Detection",
    
    // Customer Insights & Analytics
    "Customer Segmentation",
    "Customer Analytics",
    "Customer Intelligence",
    "Customer Insights",
    "Customer Data Analytics",
    "Customer Behavior Analysis",
    "Customer Profiling",
    "Customer Persona",
    "Customer Trends",
    
    // Automation & Workflows
    "Business Automation",
    "Workflow Automation",
    "Chat Automation",
    "Conversation Automation",
    "Message Automation",
    "Response Automation",
    "Reply Automation",
    "Auto-Reply",
    "Automated Responses",
    "Smart Automation",
    "Process Automation",
    "Business Process Automation",
    "Task Automation",
    "Communication Automation",
    
    // Knowledge & Information
    "Knowledge Retrieval",
    "RAG",
    "Retrieval Augmented Generation",
    "Knowledge Base",
    "Knowledge Management",
    "Information Retrieval",
    "Document Retrieval",
    "AI Knowledge Base",
    "Intelligent Search",
    "Semantic Search",
    
    // Prioritization & Routing
    "Message Prioritization",
    "Conversation Prioritization",
    "Smart Routing",
    "Intelligent Routing",
    "Automatic Routing",
    "Ticket Routing",
    "Priority Management",
    "Urgency Detection",
    
    // Security & Compliance
    "Data Security",
    "Privacy Protection",
    "GDPR Compliance",
    "SOC 2 Compliance",
    "HIPAA Compliance",
    "Data Encryption",
    "Secure Messaging",
    "Tenant Isolation",
    "Role-Based Access Control",
    "RBAC",
    "Data Protection",
    "Secure Communication",
    
    // Multi-Language Support
    "Multi-Language Support",
    "Multilingual AI",
    "Sinhala Support",
    "English Support",
    "Language Detection",
    "Translation",
    "Bilingual Support",
    "Cross-Language Communication",
    
    // SME & Small Business
    "SME Tools",
    "Small Business Tools",
    "Small Business Software",
    "Medium Business Tools",
    "SMB Software",
    "Small Business Automation",
    "SME Automation",
    "Small Business CRM",
    "SME Customer Service",
    "Small Business Solutions",
    "Startup Tools",
    "Entrepreneur Tools",
    "Local Business Tools",
    
    // Industries & Use Cases
    "E-commerce Customer Service",
    "Retail Customer Support",
    "SaaS Customer Support",
    "Online Business Tools",
    "Digital Business",
    "Online Store Support",
    "E-commerce Automation",
    "Service Business",
    "Consulting Tools",
    "Agency Tools",
    
    // Communication Platforms
    "Business Messaging",
    "Business Communication",
    "Team Communication",
    "Internal Communication",
    "Business Chat",
    "Corporate Messaging",
    "Enterprise Messaging",
    
    // Digital Assistants & Bots
    "Digital Assistants",
    "Virtual Assistants",
    "AI Virtual Assistant",
    "Chatbot",
    "Chat Bot",
    "Conversational Bot",
    "Smart Bot",
    "Intelligent Bot",
    "AI Bot",
    "Business Bot",
    "Customer Service Bot",
    "Support Bot",
    
    // Reply & Response Management
    "AI Reply Generation",
    "Smart Replies",
    "Suggested Replies",
    "Auto-Suggest Replies",
    "Reply Drafting",
    "Response Suggestions",
    "Quick Replies",
    "Templated Responses",
    "Response Management",
    
    // Productivity & Efficiency
    "Productivity Tools",
    "Business Productivity",
    "Time Saving Tools",
    "Efficiency Tools",
    "Productivity Software",
    "Work Efficiency",
    "Time Management",
    "Task Management",
    
    // Team Collaboration
    "Team Collaboration",
    "Collaborative Tools",
    "Team Communication",
    "Team Messaging",
    "Collaboration Software",
    "Team Productivity",
    "Work Collaboration",
    
    // Integration & API
    "API Integration",
    "Third-Party Integration",
    "System Integration",
    "Platform Integration",
    "Tool Integration",
    "Service Integration",
    "Connectivity",
    "Integration Platform",
    
    // Software Categories
    "SaaS",
    "Software as a Service",
    "Cloud Software",
    "Cloud-Based Solution",
    "Web Application",
    "Web App",
    "Online Software",
    "Web-Based Tool",
    "Business Software",
    "Enterprise Software",
    "B2B Software",
    "Business Tools",
    "Business Solutions",
    
    // Technology Stack (for developers)
    "React",
    "Next.js",
    "NextJS",
    "TypeScript",
    "Tailwind",
    "Tailwind CSS",
    "Tailwind V4",
    "Shadcn",
    "Shadcn UI",
    "Framer Motion",
    "Motion",
    "Design Systems",
    "Modern UI",
    "UI Components",
    "Frontend Developer",
    "Fullstack Developer",
    "Web Developer",
    "Developer Tools",
    
    // Location-Based (Sweden/Europe)
    "Sweden",
    "Swedish",
    "Stockholm",
    "Europe",
    "European",
    "Nordic",
    "Scandinavian",
    "Sri Lanka",
    "Sri Lankan",
    "Colombo",
    "Asia",    
    // Performance & Quality
    "Real-Time Processing",
    "Instant Response",
    "Fast Response Time",
    "High Performance",
    "Scalable Solution",
    "Reliable Software",
    "Efficient Processing",
    
    // Modern & Innovation
    "Modern Web Apps",
    "Next.js SaaS",
    "Modern UI Components",
    "Tech Startup",
    "Innovation",
    "Cutting-Edge Technology",
    "Advanced AI",
    "Next-Gen AI",
    "Future of Customer Service",
    
    // Free & Pricing Related
    "Free Trial",
    "Free Plan",
    "Affordable",
    "Cost-Effective",
    "Budget-Friendly",
    "Value for Money",
    
    // Alternative Terms
    "Freelancer Tools",
    "Agency Management",
    "Client Communication",
    "Project Management",
    "Business Management",
    "Operations Management",
  ],
  authors: [
    {
      name: "Sequence3",
      url: "https://sequence3.se",
    },
  ],
  creator: "Sequence3",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteUrl,
    title: siteConfig.name,
    description: siteConfig.description,
    siteName: "Sequence3",
    images: [
      {
        url: ogImageUrl,
        width: 1200,
        height: 630,
        alt: siteConfig.name,
        type: "image/png",
      },
      {
        url: `${siteUrl}/agent-template-og.png`,
        width: 1200,
        height: 630,
        alt: siteConfig.name,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: siteConfig.name,
    description: siteConfig.description,
    creator: "@sequence3",
    site: "@sequence3",
    images: [ogImageUrl],
  },
  alternates: {
    canonical: siteUrl,
  },
  category: "technology",
  classification: "Business Software",
  referrer: "origin-when-cross-origin",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  other: {
    "application-name": "Sequence3",
    "apple-mobile-web-app-title": "Sequence3",
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "black-translucent",
    "mobile-web-app-capable": "yes",
    "msapplication-TileColor": "#000000",
    "msapplication-config": "/browserconfig.xml",
    "geo.region": "LK",
    "geo.placename": "Sri Lanka",
    "language": "English",
    "rating": "general",
    "author": "Sequence3",
    "twitter:label1": "Price",
    "twitter:data1": "Free to Start",
    "twitter:label2": "Category",
    "twitter:data2": "Business Software",
    
    // Sequence3 Verified Domains
    // sq3.io / sq3.us / sq3.one / sequence3.se
    
    // Note: Add verification tags when available:
    // "google-site-verification": "your-verification-code",
    // "yandex-verification": "your-verification-code",
    // "msvalidate.01": "your-verification-code",
  },
};
